[package]
name = "starknet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { git = "https://github.com/lambdaclass/cairo-rs.git", rev = "c22a11db4e22bf324534c7b6f978a40478f85d50" }
